blank_issues_enabled: false
contact_links:
    - name: ðŸ’» Community Discord
      url: https://discord.gg/6D2dXNy82q
      about: Join our Community Discord server to chat with other users in the MicroWin community.